#==================================================================================================
#! @file      Dockerfile
#! @author    Geon Technologies (geon.tech)
#! @copyright 2022 Geon Technologies, LLC. All rights reserved.
#! @brief     A Docker image that slightly modifies the existing image
#==================================================================================================

# Start with standard image
FROM geontech/redhawk-gpp:2.2.5

# Overwrite the initialization script
COPY gpp-node-init.sh /root/gpp-node-init.sh
